set(FF_PREFIX ff)
set(FF_URL ${CMAKE_SOURCE_DIR}/libs/QCDLoop/ff)

ExternalProject_Add(${FF_PREFIX}
	SOURCE_DIR ${FF_URL}
	INSTALL_COMMAND ""
	CONFIGURE_COMMAND ""
	BUILD_IN_SOURCE 1
	BUILD_COMMAND make
)