      DOUBLE PRECISION FUNCTION SGUB_TTBUB(P1, P2, P3, P4, P5)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P1,P2,P3,P4,...
C  
C FOR PROCESS : g u~  -> t t~ u~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NEXTERNAL,   NCOMB                     
      PARAMETER (NEXTERNAL=5, NCOMB= 32)
C  
C ARGUMENTS 
C  
      DOUBLE PRECISION P1(0:3),P2(0:3),P3(0:3),P4(0:3),P5(0:3)                   
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY                                         
      DOUBLE PRECISION T
      DOUBLE PRECISION GUB_TTBUB                                                 
      INTEGER IHEL
      LOGICAL GOODHEL(NCOMB)
      DATA GOODHEL/NCOMB*.FALSE./
      DATA NTRY/0/
      DATA (NHEL(IHEL,  1),IHEL=1,5) / -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,  2),IHEL=1,5) / -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,  3),IHEL=1,5) / -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,  4),IHEL=1,5) / -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,  5),IHEL=1,5) / -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,  6),IHEL=1,5) / -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,  7),IHEL=1,5) / -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,  8),IHEL=1,5) / -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,  9),IHEL=1,5) / -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 10),IHEL=1,5) / -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 11),IHEL=1,5) / -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 12),IHEL=1,5) / -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 13),IHEL=1,5) / -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 14),IHEL=1,5) / -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 15),IHEL=1,5) / -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 16),IHEL=1,5) / -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 17),IHEL=1,5) /  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 18),IHEL=1,5) /  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 19),IHEL=1,5) /  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 20),IHEL=1,5) /  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 21),IHEL=1,5) /  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 22),IHEL=1,5) /  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 23),IHEL=1,5) /  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 24),IHEL=1,5) /  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 25),IHEL=1,5) /  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 26),IHEL=1,5) /  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 27),IHEL=1,5) /  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 28),IHEL=1,5) /  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 29),IHEL=1,5) /  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 30),IHEL=1,5) /  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 31),IHEL=1,5) /  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 32),IHEL=1,5) /  1,  1,  1,  1,  1/
C ----------
C BEGIN CODE
C ----------
      SGUB_TTBUB = 0d0
      NTRY=NTRY+1
      DO IHEL=1,NCOMB
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 10) THEN
             T=GUB_TTBUB(P1, P2, P3, P4, P5,NHEL(1,IHEL)) 
             SGUB_TTBUB = SGUB_TTBUB + T
              IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL)) THEN
                  GOODHEL(IHEL)=.TRUE.
              ENDIF
          ENDIF
      ENDDO
      SGUB_TTBUB = SGUB_TTBUB /  4D0 
      END
       
       
      DOUBLE PRECISION FUNCTION GUB_TTBUB(P1, P2, P3, P4, P5,NHEL)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT IN PHASE SPACE P1,P2,P3,P4,...
C AND HELICITY NHEL(1),NHEL(2),....
C  
C FOR PROCESS : g u~  -> t t~ u~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN,    NEXTERNAL       
      PARAMETER (NGRAPHS=  5,NEIGEN=  3,NEXTERNAL=5)    
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      DOUBLE PRECISION P1(0:3),P2(0:3),P3(0:3),P4(0:3),P5(0:3)                   
      INTEGER NHEL(NEXTERNAL)                                                    
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      DOUBLE PRECISION EIGEN_VAL(NEIGEN)
      DOUBLE PRECISION EIGEN_VEC(NGRAPHS,NEIGEN)
      DOUBLE COMPLEX ZTEMP
      DOUBLE COMPLEX AMP(NGRAPHS)
      DOUBLE COMPLEX W1(6)  , W2(6)  , W3(6)  , W4(6)  , W5(6)    
      DOUBLE COMPLEX W6(6)  , W7(6)  , W8(6)  , W9(6)  , W10(6)   
      DOUBLE COMPLEX W11(6) , W12(6) 
C  
C GLOBAL VARIABLES
C  
      DOUBLE PRECISION  GG(2), G
      COMMON /COUPQCD/ GG,    G
      DOUBLE PRECISION   FMASS(12), FWIDTH(12)
      COMMON /FERMIONS/ FMASS,     FWIDTH
C  
C COLOR DATA
C  
      DATA EIGEN_VAL(1  )/       2.777777777777777777777777777778D-02 /    
      DATA EIGEN_VEC(1  ,1  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(2  ,1  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(3  ,1  )/  -5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(4  ,1  )/   0.000000000000000000000000000000D+00 /    
      DATA EIGEN_VEC(5  ,1  )/  -5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VAL(2  )/       1.666666666666666666666666666667D-01 /    
      DATA EIGEN_VEC(1  ,2  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(2  ,2  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(3  ,2  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(4  ,2  )/   0.000000000000000000000000000000D+00 /    
      DATA EIGEN_VEC(5  ,2  )/   5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VAL(3  )/       5.000000000000000000000000000000D-01 /    
      DATA EIGEN_VEC(1  ,3  )/  -3.535533905932737622004221810524D-01 /    
      DATA EIGEN_VEC(2  ,3  )/   3.535533905932737622004221810524D-01 /    
      DATA EIGEN_VEC(3  ,3  )/   3.535533905932737622004221810524D-01 /    
      DATA EIGEN_VEC(4  ,3  )/   7.071067811865475244008443621048D-01 /    
      DATA EIGEN_VEC(5  ,3  )/  -3.535533905932737622004221810524D-01 /    
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P1  , ZERO,NHEL(1  ),-1,W1  )                            
      CALL OXXXXX(P2  ,FMASS(3  ),NHEL(2  ),-1,W2  )                       
      CALL OXXXXX(P3  ,FMASS(11 ),NHEL(3  ), 1,W3  )                       
      CALL IXXXXX(P4  ,FMASS(11 ),NHEL(4  ),-1,W4  )                       
      CALL IXXXXX(P5  ,FMASS(3  ),NHEL(5  ),-1,W5  )                       
      CALL FVIXXX(W4  ,W1  ,GG,FMASS(11 ),FWIDTH(11 ),W6  )                
      CALL JIOXXX(W5  ,W2  ,GG,ZERO,ZERO,W7  )                             
      CALL IOVXXX(W6  ,W3  ,W7  ,GG,AMP(1  ))                              
      CALL FVOXXX(W3  ,W1  ,GG,FMASS(11 ),FWIDTH(11 ),W8  )                
      CALL JIOXXX(W4  ,W8  ,GG,ZERO,ZERO,W9  )                             
      CALL IOVXXX(W5  ,W2  ,W9  ,GG,AMP(2  ))                              
      CALL JIOXXX(W4  ,W3  ,GG,ZERO,ZERO,W10 )                             
      CALL FVIXXX(W5  ,W1  ,GG,FMASS(3  ),FWIDTH(3  ),W11 )                
      CALL IOVXXX(W11 ,W2  ,W10 ,GG,AMP(3  ))                              
      CALL GGGXXX(W1  ,W7  ,W10 ,G,AMP(4  ))                               
      CALL FVOXXX(W2  ,W1  ,GG,FMASS(3  ),FWIDTH(3  ),W12 )                
      CALL IOVXXX(W5  ,W12 ,W10 ,GG,AMP(5  ))                              
      GUB_TTBUB = 0.D0 
      DO I = 1, NEIGEN
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NGRAPHS
              ZTEMP = ZTEMP + EIGEN_VEC(J,I)*AMP(J)
          ENDDO
          GUB_TTBUB =GUB_TTBUB+ZTEMP*EIGEN_VAL(I)*CONJG(ZTEMP) 
      ENDDO
C      CALL GAUGECHECK(AMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NGRAPHS,NEIGEN)
      END
