      DOUBLE PRECISION FUNCTION SUUB_TTB(P1, P2, P3, P4)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P1,P2,P3,P4,...
C  
C FOR PROCESS : u u~  -> t t~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NEXTERNAL,   NCOMB                     
      PARAMETER (NEXTERNAL=4, NCOMB= 16)
C  
C ARGUMENTS 
C  
      DOUBLE PRECISION P1(0:3),P2(0:3),P3(0:3),P4(0:3)                           
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY                                         
      DOUBLE PRECISION T
      DOUBLE PRECISION UUB_TTB                                                   
      INTEGER IHEL
      LOGICAL GOODHEL(NCOMB)
      DATA GOODHEL/NCOMB*.FALSE./
      DATA NTRY/0/
      DATA (NHEL(IHEL,  1),IHEL=1,4) / -1, -1, -1, -1/
      DATA (NHEL(IHEL,  2),IHEL=1,4) / -1, -1, -1,  1/
      DATA (NHEL(IHEL,  3),IHEL=1,4) / -1, -1,  1, -1/
      DATA (NHEL(IHEL,  4),IHEL=1,4) / -1, -1,  1,  1/
      DATA (NHEL(IHEL,  5),IHEL=1,4) / -1,  1, -1, -1/
      DATA (NHEL(IHEL,  6),IHEL=1,4) / -1,  1, -1,  1/
      DATA (NHEL(IHEL,  7),IHEL=1,4) / -1,  1,  1, -1/
      DATA (NHEL(IHEL,  8),IHEL=1,4) / -1,  1,  1,  1/
      DATA (NHEL(IHEL,  9),IHEL=1,4) /  1, -1, -1, -1/
      DATA (NHEL(IHEL, 10),IHEL=1,4) /  1, -1, -1,  1/
      DATA (NHEL(IHEL, 11),IHEL=1,4) /  1, -1,  1, -1/
      DATA (NHEL(IHEL, 12),IHEL=1,4) /  1, -1,  1,  1/
      DATA (NHEL(IHEL, 13),IHEL=1,4) /  1,  1, -1, -1/
      DATA (NHEL(IHEL, 14),IHEL=1,4) /  1,  1, -1,  1/
      DATA (NHEL(IHEL, 15),IHEL=1,4) /  1,  1,  1, -1/
      DATA (NHEL(IHEL, 16),IHEL=1,4) /  1,  1,  1,  1/
C ----------
C BEGIN CODE
C ----------
      SUUB_TTB = 0d0
      NTRY=NTRY+1
      DO IHEL=1,NCOMB
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 10) THEN
             T=UUB_TTB(P1, P2, P3, P4,NHEL(1,IHEL)) 
             SUUB_TTB = SUUB_TTB + T
              IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL)) THEN
                  GOODHEL(IHEL)=.TRUE.
              ENDIF
          ENDIF
      ENDDO
      SUUB_TTB = SUUB_TTB /  4D0 
      END
       
       
      DOUBLE PRECISION FUNCTION UUB_TTB(P1, P2, P3, P4,NHEL)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT IN PHASE SPACE P1,P2,P3,P4,...
C AND HELICITY NHEL(1),NHEL(2),....
C  
C FOR PROCESS : u u~  -> t t~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN,    NEXTERNAL       
      PARAMETER (NGRAPHS=  1,NEIGEN=  1,NEXTERNAL=4)    
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      DOUBLE PRECISION P1(0:3),P2(0:3),P3(0:3),P4(0:3)                           
      INTEGER NHEL(NEXTERNAL)                                                    
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      DOUBLE PRECISION EIGEN_VAL(NEIGEN)
      DOUBLE PRECISION EIGEN_VEC(NGRAPHS,NEIGEN)
      DOUBLE COMPLEX ZTEMP
      DOUBLE COMPLEX AMP(NGRAPHS)
      DOUBLE COMPLEX W1(6)  , W2(6)  , W3(6)  , W4(6)  , W5(6)  
C  
C GLOBAL VARIABLES
C  
      DOUBLE PRECISION  GG(2), G
      COMMON /COUPQCD/ GG,    G
      DOUBLE PRECISION   FMASS(12), FWIDTH(12)
      COMMON /FERMIONS/ FMASS,     FWIDTH
C  
C COLOR DATA
C  
      DATA EIGEN_VAL(1  )/       2.222222222222222222222222222222D-01 /    
      DATA EIGEN_VEC(1  ,1  )/  -1.000000000000000000000000000000D+00 /    
C ----------
C BEGIN CODE
C ----------
      CALL IXXXXX(P1  ,FMASS(3  ),NHEL(1  ), 1,W1  )                       
      CALL OXXXXX(P2  ,FMASS(3  ),NHEL(2  ),-1,W2  )                       
      CALL OXXXXX(P3  ,FMASS(11 ),NHEL(3  ), 1,W3  )                       
      CALL IXXXXX(P4  ,FMASS(11 ),NHEL(4  ),-1,W4  )                       
      CALL JIOXXX(W1  ,W2  ,GG,ZERO,ZERO,W5  )                             
      CALL IOVXXX(W4  ,W3  ,W5  ,GG,AMP(1  ))                              
      UUB_TTB = 0.D0 
      DO I = 1, NEIGEN
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NGRAPHS
              ZTEMP = ZTEMP + EIGEN_VEC(J,I)*AMP(J)
          ENDDO
          UUB_TTB =UUB_TTB+ZTEMP*EIGEN_VAL(I)*CONJG(ZTEMP) 
      ENDDO
C      CALL GAUGECHECK(AMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NGRAPHS,NEIGEN)
      END
